### ISSUE TITLE
GRAV not producing necessary thumbnails?

### ISSUE THREAD

**Issue by BillyHilly** [OleVik/grav-plugin-imgsrcset#3]
Hello,
Awesome plug-in, this is so forward thinking and simple. It's just not working for me b/c GRAV is not making all the thumbnails that it's putting in srcset.

My Markdown is this:
`![Intensive Logo](/images/01_Intensive-logo.jpg?lightbox=1200,800)`

The output is this:
`<a rel="lightbox" data-width="1200" data-height="800" href="/images/f/7/b/9/c/f7b9ccb9d6e4efaca0d7aab2cbc5d9c15000587c-4eb4a 77c83dc82ad3d60149cfa9d0fcd07996fa6-01intensive-logo3x.jpeg" data-srcset="/images/f/7/b/9/c/f7b9ccb9d6e4efaca0d7aab2cbc5d9c15000587 c-4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01intensive-logo3x.jpeg 850w, /images/f/0/2/0/5/f0205759a3d5ed66066b1cc084bdef2ad0addfc6-01intensive -logo3x.jpeg 2550w, /images/e/6/a/2/1/e6a215ea6247ab5894d788470d2f0fb375cde439-4f10289db8e b4f67636b083945f469b5afbd4347-01intensive-logo3x.jpeg 1700w"><img alt="Intensive Logo" src="/images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01inte nsive-logo3x.jpeg" srcset="/images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01i ntensive-logo3x-320.jpeg 320w, /images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fc d07996fa6-01intensive -logo3x-480.jpeg 480w, /images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01intensive -logo3x-640.jpeg 640w, /images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01intensive -logo3x-960.jpeg 960w, /images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01intensive -logo3x-1280.jpeg 1280w, /images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01intensive -logo3x-1600.jpeg 1600w, /images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01intensive -logo3x-1920.jpeg 1920w, /images/4/e/b/4/a/4eb4a77c83dc82ad3d60149cfa9d0fcd07996fa6-01intensive -logo3x-2240.jpeg 2240w" sizes="100vw"></a>`
The a href works, and so does the img src.
But checked out the paths on img srcset and the cached thumbnails aren't being created it seems.
What am I doing wrong?

**Comment by OleVik** [comment]
It is worth noting that this plugin does not try to leverage Grav's media caching mechanisms. Rather, it is a simple attempt to circumvent it by assuming the images are generated outside of Grav.

That said, are you generating the thumbnails through Twig or Grav? And can you verify that the images exist in cache? Because Grav's caching is not optimal for generating many images from large images - indeed it tends to crash both caching and Grav itself - I tend to generate them using Node rather than rely on Grav, as it is more reliable and massively faster. For an example, see [this gist](https://gist.github.com/OleVik/f2c8b51a7153743b13607072c27cf8d2).
